language: go

go:
  - "1.14"

go_import_path: github.com/openkruise/kruise

script:
  - ./scripts/travis-test.sh

after_success:
  - ./hack/docker_build_daily.sh
  - bash <(curl -s https://codecov.io/bash) || echo "Failed to report code coverage!"
